name: go212
description: GO212 - La Super App Marocaine
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^8.1.0
  smooth_page_indicator: ^2.0.1
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  iconsax: ^0.0.8
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.3
  feature_gofix:
    path: ../../packages/features/feature_gofix
  flutter_bloc: ^8.1.6
  video_player: ^2.11.1
  intl: ^0.20.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/gowash/
    - assets/images/gowash/packs/
    - assets/images/gowash/brands/
    - assets/images/videos/
    - assets/images/videos/gowash_intro.mp4
    - assets/animations/
