const fs = require('fs');
const B = 'C:/Users/HP ElieBook/Desktop/goo212/Supper-App-Go212/lib';

const lines = [
"// ignore_for_file: deprecated_member_use",
"import 'dart:math' as math;",
"import 'package:flutter/material.dart';",
"",
"class HomeScreen extends StatelessWidget {",
"  final ValueChanged<int>? onTabChange;",
"  const HomeScreen({super.key, this.onTabChange});",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    return Scaffold(",
"      backgroundColor: const Color(0xFF0D3D26),",
"      body: Stack(",
"        children: [",
"          // ── Zellige background ─────────────────────────",
"          Positioned.fill(child: CustomPaint(painter: _ZelligeBgPainter())),",
"          // ── Dark gradient overlay ──────────────────────",
"          Positioned.fill(",
"            child: DecoratedBox(",
"              decoration: BoxDecoration(",
"                gradient: LinearGradient(",
"                  begin: Alignment.topCenter,",
"                  end: Alignment.bottomCenter,",
"                  colors: [",
"                    const Color(0xFF0D3D26).withOpacity(0.92),",
"                    const Color(0xFF166534).withOpacity(0.80),",
"                    const Color(0xFF0D3D26).withOpacity(0.96),",
"                  ],",
"                  stops: const [0, 0.5, 1],",
"                ),",
"              ),",
"            ),",
"          ),",
"          // ── Content ────────────────────────────────────",
"          SafeArea(",
"            bottom: false,",
"            child: Column(",
"              children: [",
"                _TopBar(),",
"                _HeroSection(),",
"                const SizedBox(height: 8),",
"                Expanded(child: _ServicesGrid(onTabChange: onTabChange)),",
"                _BottomNavBar(onTabChange: onTabChange),",
"              ],",
"            ),",
"          ),",
"        ],",
"      ),",
"    );",
"  }",
"}",
"",
"// ─── Top Bar ──────────────────────────────────────────────────────────────────",
"class _TopBar extends StatelessWidget {",
"  @override",
"  Widget build(BuildContext context) {",
"    return Padding(",
"      padding: const EdgeInsets.fromLTRB(20, 16, 20, 0),",
"      child: Row(",
"        children: [",
"          // Logo + Tagline",
"          Column(",
"            crossAxisAlignment: CrossAxisAlignment.start,",
"            children: [",
"              Row(",
"                children: [",
"                  Container(",
"                    padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),",
"                    decoration: BoxDecoration(",
"                      color: const Color(0xFFFFD700).withOpacity(0.15),",
"                      borderRadius: BorderRadius.circular(8),",
"                      border: Border.all(color: const Color(0xFFFFD700).withOpacity(0.4)),",
"                    ),",
"                    child: const Text('GO212',",
"                        style: TextStyle(fontFamily: 'Georgia', fontSize: 22,",
"                            fontWeight: FontWeight.w900, color: Color(0xFFFFD700), letterSpacing: 3)),",
"                  ),",
"                  const SizedBox(width: 8),",
"                  Container(",
"                    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),",
"                    decoration: BoxDecoration(",
"                      color: Colors.white.withOpacity(0.1),",
"                      borderRadius: BorderRadius.circular(6),",
"                    ),",
"                    child: const Text('\u2605 Casa',",
"                        style: TextStyle(color: Colors.white70, fontSize: 11, fontWeight: FontWeight.w600)),",
"                  ),",
"                ],",
"              ),",
"              const SizedBox(height: 2),",
"              Text('Bouge malin au Maroc',",
"                  style: TextStyle(color: Colors.white.withOpacity(0.55), fontSize: 11)),",
"            ],",
"          ),",
"          const Spacer(),",
"          // Notification bell",
"          GestureDetector(",
"            onTap: () => Navigator.pushNamed(context, '/notifications'),",
"            child: Container(",
"              width: 42, height: 42,",
"              decoration: BoxDecoration(",
"                color: Colors.white.withOpacity(0.1),",
"                shape: BoxShape.circle,",
"                border: Border.all(color: Colors.white.withOpacity(0.2)),",
"              ),",
"              child: Stack(",
"                alignment: Alignment.center,",
"                children: [",
"                  const Icon(Icons.notifications_outlined, color: Colors.white, size: 22),",
"                  Positioned(",
"                    top: 8, right: 8,",
"                    child: Container(",
"                      width: 7, height: 7,",
"                      decoration: const BoxDecoration(",
"                        color: Color(0xFFFF5252), shape: BoxShape.circle),",
"                    ),",
"                  ),",
"                ],",
"              ),",
"            ),",
"          ),",
"          const SizedBox(width: 10),",
"          // Profile avatar",
"          GestureDetector(",
"            onTap: () => Navigator.pushNamed(context, '/profile'),",
"            child: Container(",
"              width: 42, height: 42,",
"              decoration: BoxDecoration(",
"                gradient: const LinearGradient(",
"                  colors: [Color(0xFFFFD700), Color(0xFFFFA500)],",
"                ),",
"                shape: BoxShape.circle,",
"                border: Border.all(color: Colors.white.withOpacity(0.3), width: 2),",
"              ),",
"              child: const Icon(Icons.person_rounded, color: Colors.white, size: 22),",
"            ),",
"          ),",
"        ],",
"      ),",
"    );",
"  }",
"}",
"",
"// ─── Hero Section ─────────────────────────────────────────────────────────────",
"class _HeroSection extends StatelessWidget {",
"  @override",
"  Widget build(BuildContext context) {",
"    return Padding(",
"      padding: const EdgeInsets.fromLTRB(20, 20, 20, 8),",
"      child: Row(",
"        children: [",
"          // Text side",
"          Expanded(",
"            child: Column(",
"              crossAxisAlignment: CrossAxisAlignment.start,",
"              children: [",
"                const Text('Salut ! \uD83D\uDC4B',",
"                    style: TextStyle(color: Colors.white70, fontSize: 14, fontWeight: FontWeight.w500)),",
"                const SizedBox(height: 4),",
"                const Text('O\u00f9 vas-tu\\naujourd\\'hui ?',",
"                    style: TextStyle(color: Colors.white, fontSize: 26,",
"                        fontWeight: FontWeight.w900, height: 1.15)),",
"                const SizedBox(height: 14),",
"                // Search bar",
"                Container(",
"                  height: 46,",
"                  decoration: BoxDecoration(",
"                    color: Colors.white.withOpacity(0.12),",
"                    borderRadius: BorderRadius.circular(14),",
"                    border: Border.all(color: Colors.white.withOpacity(0.2)),",
"                  ),",
"                  child: Row(",
"                    children: [",
"                      const SizedBox(width: 14),",
"                      Icon(Icons.search_rounded, color: Colors.white.withOpacity(0.6), size: 20),",
"                      const SizedBox(width: 8),",
"                      Text('Chercher un service...',",
"                          style: TextStyle(color: Colors.white.withOpacity(0.5), fontSize: 13)),",
"                    ],",
"                  ),",
"                ),",
"              ],",
"            ),",
"          ),",
"          const SizedBox(width: 12),",
"          // Mascot",
"          Image.asset('assets/images/mascot.png', height: 120, fit: BoxFit.contain),",
"        ],",
"      ),",
"    );",
"  }",
"}",
"",
"// ─── Services Grid ────────────────────────────────────────────────────────────",
"class _ServicesGrid extends StatelessWidget {",
"  final ValueChanged<int>? onTabChange;",
"  const _ServicesGrid({this.onTabChange});",
"",
"  static const _services = [",
"    _Service('GoRide', 'assets/images/goride.png', '\uD83D\uDEF5', Color(0xFF16A34A),",
"        'Location moto', '/goride/transition', null),",
"    _Service('GoWash', 'assets/images/gowash.png', '\uD83D\uDCA6', Color(0xFF2563EB),",
"        'Lavage \u00e0 domicile', '/gowash', null),",
"    _Service('GoBike', 'assets/images/gobike.png', '\uD83D\uDEB4', Color(0xFF7C3AED),",
"        'V\u00e9lo & trottinette', null, null),",
"    _Service('GoFix', 'assets/images/gofix.png', '\uD83D\uDD27', Color(0xFFDC2626),",
"        'R\u00e9paration express', null, null),",
"    _Service('GoShop', 'assets/images/goshop.png', '\uD83D\uDED2', Color(0xFFF59E0B),",
"        'Accessoires moto', null, null),",
"    _Service('Explorer', null, '\uD83E\uDDED', Color(0xFF0891B2),",
"        'Voir tout', '/explore', null),",
"  ];",
"",
"  void _navigate(BuildContext context, _Service s) {",
"    if (s.route != null) {",
"      Navigator.pushNamed(context, s.route!);",
"    }",
"  }",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    return Container(",
"      margin: const EdgeInsets.fromLTRB(16, 0, 16, 0),",
"      child: Column(",
"        crossAxisAlignment: CrossAxisAlignment.start,",
"        children: [",
"          Padding(",
"            padding: const EdgeInsets.only(left: 4, bottom: 12),",
"            child: Row(",
"              children: [",
"                const Text('Nos services',",
"                    style: TextStyle(color: Colors.white, fontSize: 16,",
"                        fontWeight: FontWeight.w800, letterSpacing: 0.3)),",
"                const SizedBox(width: 8),",
"                Container(",
"                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),",
"                  decoration: BoxDecoration(",
"                    color: const Color(0xFFFFD700).withOpacity(0.15),",
"                    borderRadius: BorderRadius.circular(6),",
"                    border: Border.all(color: const Color(0xFFFFD700).withOpacity(0.3)),",
"                  ),",
"                  child: const Text('Casa', style: TextStyle(color: Color(0xFFFFD700),",
"                      fontSize: 10, fontWeight: FontWeight.w700)),",
"                ),",
"              ],",
"            ),",
"          ),",
"          Expanded(",
"            child: GridView.builder(",
"              physics: const NeverScrollableScrollPhysics(),",
"              gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(",
"                crossAxisCount: 3,",
"                childAspectRatio: 0.85,",
"                crossAxisSpacing: 12,",
"                mainAxisSpacing: 12,",
"              ),",
"              itemCount: _services.length,",
"              itemBuilder: (ctx, i) => _ServiceTile(",
"                service: _services[i],",
"                onTap: () => _navigate(context, _services[i]),",
"              ),",
"            ),",
"          ),",
"        ],",
"      ),",
"    );",
"  }",
"}",
"",
"class _ServiceTile extends StatefulWidget {",
"  final _Service service;",
"  final VoidCallback onTap;",
"  const _ServiceTile({required this.service, required this.onTap});",
"  @override",
"  State<_ServiceTile> createState() => _ServiceTileState();",
"}",
"class _ServiceTileState extends State<_ServiceTile> with SingleTickerProviderStateMixin {",
"  late AnimationController _ac;",
"  late Animation<double> _sc;",
"  @override",
"  void initState() {",
"    super.initState();",
"    _ac = AnimationController(vsync: this, duration: const Duration(milliseconds: 120));",
"    _sc = Tween(begin: 1.0, end: 0.93).animate(CurvedAnimation(parent: _ac, curve: Curves.easeOut));",
"  }",
"  @override",
"  void dispose() { _ac.dispose(); super.dispose(); }",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    final s = widget.service;",
"    final isMain = s.name != 'Explorer';",
"    return GestureDetector(",
"      onTapDown: (_) => _ac.forward(),",
"      onTapUp: (_) { _ac.reverse(); widget.onTap(); },",
"      onTapCancel: () => _ac.reverse(),",
"      child: ScaleTransition(",
"        scale: _sc,",
"        child: Container(",
"          decoration: BoxDecoration(",
"            gradient: LinearGradient(",
"              begin: Alignment.topLeft,",
"              end: Alignment.bottomRight,",
"              colors: [",
"                s.color.withOpacity(0.22),",
"                s.color.withOpacity(0.10),",
"              ],",
"            ),",
"            borderRadius: BorderRadius.circular(20),",
"            border: Border.all(color: s.color.withOpacity(0.3), width: 1.5),",
"          ),",
"          child: Padding(",
"            padding: const EdgeInsets.all(10),",
"            child: Column(",
"              mainAxisAlignment: MainAxisAlignment.center,",
"              children: [",
"                // Icon area",
"                Expanded(",
"                  child: Center(",
"                    child: s.imagePath != null",
"                        ? Image.asset(s.imagePath!, fit: BoxFit.contain)",
"                        : Text(s.fallbackEmoji,",
"                            style: const TextStyle(fontSize: 36)),",
"                  ),",
"                ),",
"                const SizedBox(height: 6),",
"                // Service name",
"                Text(s.name,",
"                    style: const TextStyle(",
"                        color: Colors.white,",
"                        fontSize: 12,",
"                        fontWeight: FontWeight.w800),",
"                    textAlign: TextAlign.center),",
"                const SizedBox(height: 2),",
"                // Subtitle",
"                Text(s.subtitle,",
"                    style: TextStyle(color: Colors.white.withOpacity(0.55), fontSize: 9.5),",
"                    textAlign: TextAlign.center,",
"                    maxLines: 1,",
"                    overflow: TextOverflow.ellipsis),",
"                // Available badge",
"                if (!isMain) ...[",
"                  const SizedBox(height: 4),",
"                  Container(",
"                    padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),",
"                    decoration: BoxDecoration(",
"                      color: s.color.withOpacity(0.2),",
"                      borderRadius: BorderRadius.circular(4),",
"                    ),",
"                    child: Text('Voir', style: TextStyle(",
"                        fontSize: 8, fontWeight: FontWeight.w700, color: s.color)),",
"                  ),",
"                ],",
"              ],",
"            ),",
"          ),",
"        ),",
"      ),",
"    );",
"  }",
"}",
"",
"// ─── Bottom Nav ───────────────────────────────────────────────────────────────",
"class _BottomNavBar extends StatelessWidget {",
"  final ValueChanged<int>? onTabChange;",
"  const _BottomNavBar({this.onTabChange});",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    return Container(",
"      height: 62 + MediaQuery.of(context).padding.bottom,",
"      decoration: BoxDecoration(",
"        color: const Color(0xFF0A2E1A),",
"        border: Border(top: BorderSide(color: Colors.white.withOpacity(0.08))),",
"      ),",
"      padding: EdgeInsets.only(bottom: MediaQuery.of(context).padding.bottom),",
"      child: Row(",
"        mainAxisAlignment: MainAxisAlignment.spaceAround,",
"        children: [",
"          _NavItem(icon: Icons.home_rounded, label: 'Accueil', active: true, onTap: () => onTabChange?.call(0)),",
"          _NavItem(icon: Icons.explore_rounded, label: 'Explorer', onTap: () => onTabChange?.call(1)),",
"          _NavItem(icon: Icons.receipt_long_rounded, label: 'Commandes', onTap: () => onTabChange?.call(2)),",
"          _NavItem(icon: Icons.person_rounded, label: 'Profil', onTap: () => onTabChange?.call(3)),",
"        ],",
"      ),",
"    );",
"  }",
"}",
"",
"class _NavItem extends StatelessWidget {",
"  final IconData icon;",
"  final String label;",
"  final bool active;",
"  final VoidCallback? onTap;",
"  const _NavItem({required this.icon, required this.label, this.active = false, this.onTap});",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    final color = active ? const Color(0xFF4ADE80) : Colors.white.withOpacity(0.45);",
"    return GestureDetector(",
"      onTap: onTap,",
"      child: Padding(",
"        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),",
"        child: Column(",
"          mainAxisSize: MainAxisSize.min,",
"          children: [",
"            Icon(icon, color: color, size: 24),",
"            const SizedBox(height: 3),",
"            Text(label, style: TextStyle(color: color, fontSize: 9.5, fontWeight: FontWeight.w600)),",
"          ],",
"        ),",
"      ),",
"    );",
"  }",
"}",
"",
"// ─── Zellige Background Painter ───────────────────────────────────────────────",
"class _ZelligeBgPainter extends CustomPainter {",
"  @override",
"  void paint(Canvas canvas, Size size) {",
"    final p = Paint()",
"      ..style = PaintingStyle.stroke",
"      ..strokeWidth = 0.8",
"      ..color = const Color(0xFF4ADE80).withOpacity(0.07);",
"    const ts = 36.0;",
"    final cols = (size.width / ts).ceil() + 2;",
"    final rows = (size.height / ts).ceil() + 2;",
"    for (int r = 0; r < rows; r++) {",
"      for (int c = 0; c < cols; c++) {",
"        final cx = c * ts + (r.isOdd ? ts / 2 : 0);",
"        final cy = r * ts;",
"        final rect = Rect.fromCenter(center: Offset(cx, cy), width: ts * 0.72, height: ts * 0.72);",
"        canvas.save();",
"        canvas.translate(cx, cy);",
"        canvas.rotate(math.pi / 4);",
"        canvas.translate(-cx, -cy);",
"        canvas.drawRect(rect, p);",
"        canvas.restore();",
"      }",
"    }",
"  }",
"",
"  @override",
"  bool shouldRepaint(covariant CustomPainter o) => false;",
"}",
"",
"// ─── Data class ───────────────────────────────────────────────────────────────",
"class _Service {",
"  final String name, fallbackEmoji, subtitle;",
"  final String? imagePath, route;",
"  final Color color;",
"  const _Service(this.name, this.imagePath, this.fallbackEmoji, this.color, this.subtitle, this.route, _);",
"}",
].join('\n');

const BPATH = 'C:/Users/HP ElieBook/Desktop/goo212/Supper-App-Go212/lib';
fs.writeFileSync(BPATH + '/features/home/home_screen.dart', lines, 'utf8');
console.log('home_screen done');
