const fs = require('fs');
const B = 'C:/Users/HP ElieBook/Desktop/goo212/Supper-App-Go212/lib';

const lines = [
"// ignore_for_file: deprecated_member_use",
"import 'package:flutter/material.dart';",
"import '../../../core/theme/go212_colors.dart';",
"import '../models/goride_booking_model.dart';",
"import '../widgets/goride_btn.dart';",
"import '../widgets/zellige_header.dart';",
"",
"class GoRideDeliveryScreen extends StatefulWidget {",
"  const GoRideDeliveryScreen({super.key});",
"  @override",
"  State<GoRideDeliveryScreen> createState() => _GoRideDeliveryScreenState();",
"}",
"",
"class _GoRideDeliveryScreenState extends State<GoRideDeliveryScreen>",
"    with SingleTickerProviderStateMixin {",
"  String? _selected;",
"  late AnimationController _anim;",
"  late Animation<double> _fade;",
"",
"  @override",
"  void initState() {",
"    super.initState();",
"    _anim = AnimationController(vsync: this, duration: const Duration(milliseconds: 450));",
"    _fade = CurvedAnimation(parent: _anim, curve: Curves.easeOut);",
"    _anim.forward();",
"  }",
"",
"  @override",
"  void dispose() { _anim.dispose(); super.dispose(); }",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    final booking = ModalRoute.of(context)?.settings.arguments as GoRideBooking? ?? const GoRideBooking();",
"    return Scaffold(",
"      backgroundColor: Colors.white,",
"      body: Column(",
"        children: [",
"          _buildHeader(context),",
"          Expanded(",
"            child: FadeTransition(",
"              opacity: _fade,",
"              child: SingleChildScrollView(",
"                padding: const EdgeInsets.fromLTRB(20, 20, 20, 10),",
"                child: Column(",
"                  children: [",
"                    _buildCard(",
"                      key: 'livraison',",
"                      emoji: '\uD83D\uDEF5',",
"                      title: 'Livraison \u00e0 domicile',",
"                      info: '30\u201345 min \u00b7 Zone Casablanca',",
"                      badge: 'Recommand\u00e9',",
"                      badgeColor: Go212Colors.primary600,",
"                      color: Go212Colors.primary600,",
"                    ),",
"                    const SizedBox(height: 14),",
"                    _buildCard(",
"                      key: 'agence',",
"                      emoji: '\uD83C\uDFEA',",
"                      title: 'Retrait en agence',",
"                      info: '611, Rue Goulmima \u00b7 Bourgogne',",
"                      badge: 'Gratuit',",
"                      badgeColor: const Color(0xFF8B5CF6),",
"                      color: const Color(0xFF8B5CF6),",
"                    ),",
"                    const SizedBox(height: 20),",
"                    if (_selected == 'agence') _buildAgenceBanner(),",
"                    if (_selected == 'livraison') _buildLivraisonBanner(),",
"                  ],",
"                ),",
"              ),",
"            ),",
"          ),",
"          _buildFooter(context, booking),",
"        ],",
"      ),",
"    );",
"  }",
"",
"  Widget _buildHeader(BuildContext context) {",
"    return ZelligeHeader(",
"      gradientColors: const [Color(0xFF0D3D26), Color(0xFF166534), Color(0xFF16A34A)],",
"      patternOpacity: 0.08,",
"      tileSize: 28.0,",
"      child: SafeArea(",
"        bottom: false,",
"        child: Padding(",
"          padding: const EdgeInsets.fromLTRB(20, 12, 20, 20),",
"          child: Column(",
"            crossAxisAlignment: CrossAxisAlignment.start,",
"            children: [",
"              Row(",
"                children: [",
"                  GestureDetector(",
"                    onTap: () => Navigator.pop(context),",
"                    child: Container(",
"                      width: 40, height: 40,",
"                      decoration: BoxDecoration(",
"                        color: Colors.white.withOpacity(0.15),",
"                        borderRadius: BorderRadius.circular(12),",
"                        border: Border.all(color: Colors.white.withOpacity(0.25)),",
"                      ),",
"                      child: const Icon(Icons.arrow_back_rounded, color: Colors.white, size: 20),",
"                    ),",
"                  ),",
"                  const Spacer(),",
"                  const MotoMascotBadge(size: 36),",
"                  const SizedBox(width: 10),",
"                  Container(",
"                    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 5),",
"                    decoration: BoxDecoration(",
"                      color: Colors.white.withOpacity(0.18),",
"                      borderRadius: BorderRadius.circular(10),",
"                    ),",
"                    child: const Text('4 / 6',",
"                        style: TextStyle(color: Colors.white, fontSize: 12, fontWeight: FontWeight.w700)),",
"                  ),",
"                ],",
"              ),",
"              const SizedBox(height: 16),",
"              const Text('R\u00e9ception de la moto',",
"                  style: TextStyle(color: Colors.white, fontSize: 22, fontWeight: FontWeight.w800)),",
"              const SizedBox(height: 4),",
"              Text('Livraison ou retrait',",
"                  style: TextStyle(color: Colors.white.withOpacity(0.8), fontSize: 13)),",
"            ],",
"          ),",
"        ),",
"      ),",
"    );",
"  }",
"",
"  Widget _buildCard({",
"    required String key,",
"    required String emoji,",
"    required String title,",
"    required String info,",
"    required String badge,",
"    required Color badgeColor,",
"    required Color color,",
"  }) {",
"    final isSelected = _selected == key;",
"    return GestureDetector(",
"      onTap: () => setState(() => _selected = key),",
"      child: AnimatedContainer(",
"        duration: const Duration(milliseconds: 250),",
"        padding: const EdgeInsets.all(20),",
"        decoration: BoxDecoration(",
"          color: isSelected ? color.withOpacity(0.06) : Colors.white,",
"          borderRadius: BorderRadius.circular(22),",
"          border: Border.all(",
"            color: isSelected ? color : const Color(0xFFE2E8F0),",
"            width: isSelected ? 2 : 1.5,",
"          ),",
"          boxShadow: isSelected",
"              ? [BoxShadow(color: color.withOpacity(0.14), blurRadius: 16, offset: const Offset(0, 6))]",
"              : [BoxShadow(color: Colors.black.withOpacity(0.04), blurRadius: 8, offset: const Offset(0, 3))],",
"        ),",
"        child: Row(",
"          children: [",
"            Container(",
"              width: 68, height: 68,",
"              decoration: BoxDecoration(",
"                color: color.withOpacity(isSelected ? 0.12 : 0.07),",
"                borderRadius: BorderRadius.circular(20),",
"              ),",
"              child: Center(child: Text(emoji, style: const TextStyle(fontSize: 32))),",
"            ),",
"            const SizedBox(width: 16),",
"            Expanded(",
"              child: Column(",
"                crossAxisAlignment: CrossAxisAlignment.start,",
"                children: [",
"                  Row(",
"                    children: [",
"                      Flexible(",
"                        child: Text(title,",
"                            style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w700,",
"                                color: Color(0xFF1E293B))),",
"                      ),",
"                      const SizedBox(width: 8),",
"                      Container(",
"                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),",
"                        decoration: BoxDecoration(",
"                          color: badgeColor.withOpacity(0.1),",
"                          borderRadius: BorderRadius.circular(6),",
"                        ),",
"                        child: Text(badge,",
"                            style: TextStyle(fontSize: 10, fontWeight: FontWeight.w700, color: badgeColor)),",
"                      ),",
"                    ],",
"                  ),",
"                  const SizedBox(height: 6),",
"                  Text(info, style: const TextStyle(fontSize: 12.5, color: Color(0xFF64748B))),",
"                ],",
"              ),",
"            ),",
"            const SizedBox(width: 10),",
"            AnimatedContainer(",
"              duration: const Duration(milliseconds: 200),",
"              width: 26, height: 26,",
"              decoration: BoxDecoration(",
"                color: isSelected ? color : Colors.transparent,",
"                shape: BoxShape.circle,",
"                border: Border.all(color: isSelected ? color : const Color(0xFFCBD5E1), width: 2),",
"              ),",
"              child: isSelected ? const Icon(Icons.check_rounded, size: 14, color: Colors.white) : null,",
"            ),",
"          ],",
"        ),",
"      ),",
"    );",
"  }",
"",
"  Widget _buildAgenceBanner() {",
"    return Container(",
"      padding: const EdgeInsets.all(16),",
"      decoration: BoxDecoration(",
"        color: const Color(0xFFF5F3FF),",
"        borderRadius: BorderRadius.circular(16),",
"        border: Border.all(color: const Color(0xFFDDD6FE)),",
"      ),",
"      child: const Row(",
"        children: [",
"          Text('\uD83D\uDDFA\uFE0F', style: TextStyle(fontSize: 24)),",
"          SizedBox(width: 12),",
"          Expanded(",
"            child: Column(",
"              crossAxisAlignment: CrossAxisAlignment.start,",
"              children: [",
"                Text('GO212 Bourgogne',",
"                    style: TextStyle(fontSize: 13, fontWeight: FontWeight.w700, color: Color(0xFF4C1D95))),",
"                SizedBox(height: 2),",
"                Text('611, Rue Goulmima \u00b7 Lun\u2013Sam 8h\u201320h',",
"                    style: TextStyle(fontSize: 11, color: Color(0xFF6D28D9))),",
"              ],",
"            ),",
"          ),",
"        ],",
"      ),",
"    );",
"  }",
"",
"  Widget _buildLivraisonBanner() {",
"    return Container(",
"      padding: const EdgeInsets.all(16),",
"      decoration: BoxDecoration(",
"        color: const Color(0xFFF0FDF4),",
"        borderRadius: BorderRadius.circular(16),",
"        border: Border.all(color: const Color(0xFFBBF7D0)),",
"      ),",
"      child: const Row(",
"        children: [",
"          Text('\u23F1\uFE0F', style: TextStyle(fontSize: 24)),",
"          SizedBox(width: 12),",
"          Expanded(",
"            child: Column(",
"              crossAxisAlignment: CrossAxisAlignment.start,",
"              children: [",
"                Text('Livraison rapide',",
"                    style: TextStyle(fontSize: 13, fontWeight: FontWeight.w700, color: Color(0xFF166534))),",
"                SizedBox(height: 2),",
"                Text('30\u201345 min \u00b7 Assurance incluse',",
"                    style: TextStyle(fontSize: 11, color: Color(0xFF4B7A5A))),",
"              ],",
"            ),",
"          ),",
"        ],",
"      ),",
"    );",
"  }",
"",
"  Widget _buildFooter(BuildContext context, GoRideBooking booking) {",
"    return Container(",
"      padding: EdgeInsets.fromLTRB(20, 14, 20, MediaQuery.of(context).padding.bottom + 14),",
"      decoration: BoxDecoration(",
"        color: Colors.white,",
"        boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.06), blurRadius: 20, offset: const Offset(0, -4))],",
"      ),",
"      child: GoRideBtn(",
"        label: 'Continuer',",
"        onTap: _selected != null",
"            ? () {",
"                final updated = booking.copyWith(deliveryType: _selected);",
"                if (_selected == 'agence') {",
"                  Navigator.pushNamed(context, '/goride/booking/agence', arguments: updated);",
"                } else {",
"                  Navigator.pushNamed(context, '/goride/booking/summary', arguments: updated);",
"                }",
"              }",
"            : null,",
"      ),",
"    );",
"  }",
"}",
].join('\n');

fs.writeFileSync(B + '/features/goride/booking/goride_delivery_screen.dart', lines, 'utf8');
console.log('delivery done');
