const fs = require('fs');
const B = 'C:/Users/HP ElieBook/Desktop/goo212/Supper-App-Go212/lib';

const duration = [
"// ignore_for_file: deprecated_member_use",
"import 'package:flutter/material.dart';",
"import '../models/goride_booking_model.dart';",
"import 'goride_booking_shell.dart';",
"",
"class GoRideDurationScreen extends StatefulWidget {",
"  const GoRideDurationScreen({super.key});",
"  @override",
"  State<GoRideDurationScreen> createState() => _GoRideDurationScreenState();",
"}",
"",
"class _GoRideDurationScreenState extends State<GoRideDurationScreen>",
"    with SingleTickerProviderStateMixin {",
"  String? _selected;",
"  late AnimationController _anim;",
"  late Animation<double> _fade;",
"",
"  static const _items = [",
"    _DItem('heure',   '\u26A1', 'A l\\'heure',  '30',  'DH/h',    Color(0xFF3B82F6), ''),",
"    _DItem('jour',    '\u2600\uFE0F', 'Journee',  '150', 'DH/j',    Color(0xFFF59E0B), 'POPULAIRE'),",
"    _DItem('semaine', '\u2B50', 'Semaine',       '800', 'DH/sem',  Color(0xFF8B5CF6), 'TOP'),",
"    _DItem('mois',    '\uD83D\uDC8E', 'Mois',    '2500','DH/mois', Color(0xFF10B981), 'PROMO'),",
"  ];",
"",
"  @override",
"  void initState() {",
"    super.initState();",
"    _anim = AnimationController(vsync: this, duration: const Duration(milliseconds: 450));",
"    _fade = CurvedAnimation(parent: _anim, curve: Curves.easeOut);",
"    _anim.forward();",
"  }",
"",
"  @override",
"  void dispose() { _anim.dispose(); super.dispose(); }",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    final booking = ModalRoute.of(context)?.settings.arguments as GoRideBooking? ?? const GoRideBooking();",
"    return GoRideBookingShell(",
"      step: 2, totalSteps: 6,",
"      title: 'Quelle dur\\u00e9e ?',",
"      subtitle: 'Choisissez votre formule',",
"      child: FadeTransition(",
"        opacity: _fade,",
"        child: Padding(",
"          padding: const EdgeInsets.fromLTRB(4, 20, 4, 10),",
"          child: GridView.count(",
"            crossAxisCount: 2, shrinkWrap: true,",
"            physics: const NeverScrollableScrollPhysics(),",
"            crossAxisSpacing: 14, mainAxisSpacing: 14,",
"            childAspectRatio: 1.0,",
"            children: _items.map((item) => _DurCard(",
"              item: item,",
"              isSelected: _selected == item.key,",
"              onTap: () => setState(() => _selected = item.key),",
"            )).toList(),",
"          ),",
"        ),",
"      ),",
"      onNext: _selected != null",
"          ? () => Navigator.pushNamed(context, '/goride/booking/details',",
"              arguments: booking.copyWith(duration: _selected))",
"          : null,",
"    );",
"  }",
"}",
"",
"class _DurCard extends StatelessWidget {",
"  final _DItem item;",
"  final bool isSelected;",
"  final VoidCallback onTap;",
"  const _DurCard({required this.item, required this.isSelected, required this.onTap});",
"",
"  @override",
"  Widget build(BuildContext context) {",
"    return GestureDetector(",
"      onTap: onTap,",
"      child: AnimatedContainer(",
"        duration: const Duration(milliseconds: 250),",
"        curve: Curves.easeOutCubic,",
"        decoration: BoxDecoration(",
"          gradient: isSelected",
"              ? LinearGradient(begin: Alignment.topLeft, end: Alignment.bottomRight,",
"                  colors: [item.color, item.color.withOpacity(0.72)])",
"              : const LinearGradient(colors: [Colors.white, Colors.white]),",
"          borderRadius: BorderRadius.circular(22),",
"          border: Border.all(",
"            color: isSelected ? item.color : const Color(0xFFE2E8F0),",
"            width: isSelected ? 0 : 1.5,",
"          ),",
"          boxShadow: isSelected",
"              ? [BoxShadow(color: item.color.withOpacity(0.30), blurRadius: 20, offset: const Offset(0, 8))]",
"              : [BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 10, offset: const Offset(0, 3))],",
"        ),",
"        child: Padding(",
"          padding: const EdgeInsets.all(16),",
"          child: Column(",
"            crossAxisAlignment: CrossAxisAlignment.start,",
"            children: [",
"              Row(",
"                mainAxisAlignment: MainAxisAlignment.spaceBetween,",
"                children: [",
"                  Text(item.emoji, style: const TextStyle(fontSize: 26)),",
"                  if (item.badge.isNotEmpty)",
"                    Container(",
"                      padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 3),",
"                      decoration: BoxDecoration(",
"                        color: isSelected ? Colors.white.withOpacity(0.25) : item.color.withOpacity(0.12),",
"                        borderRadius: BorderRadius.circular(6),",
"                      ),",
"                      child: Text(item.badge, style: TextStyle(fontSize: 9, fontWeight: FontWeight.w800,",
"                          color: isSelected ? Colors.white : item.color, letterSpacing: 0.4)),",
"                    ),",
"                ],",
"              ),",
"              const Spacer(),",
"              Text(item.label, style: TextStyle(fontSize: 15, fontWeight: FontWeight.w800,",
"                  color: isSelected ? Colors.white : const Color(0xFF1E293B))),",
"              const SizedBox(height: 4),",
"              Row(crossAxisAlignment: CrossAxisAlignment.end, children: [",
"                Text(item.price, style: TextStyle(fontSize: 22, fontWeight: FontWeight.w900,",
"                    color: isSelected ? Colors.white : item.color)),",
"                Padding(padding: const EdgeInsets.only(bottom: 2, left: 3),",
"                  child: Text(item.unit, style: TextStyle(fontSize: 10, fontWeight: FontWeight.w600,",
"                      color: isSelected ? Colors.white.withOpacity(0.75) : const Color(0xFF94A3B8)))),",
"              ]),",
"              if (isSelected) ...[",
"                const SizedBox(height: 6),",
"                Align(alignment: Alignment.centerRight,",
"                  child: Container(width: 22, height: 22,",
"                    decoration: BoxDecoration(color: Colors.white.withOpacity(0.25), shape: BoxShape.circle),",
"                    child: const Icon(Icons.check_rounded, size: 13, color: Colors.white))),",
"              ],",
"            ],",
"          ),",
"        ),",
"      ),",
"    );",
"  }",
"}",
"",
"class _DItem {",
"  final String key, emoji, label, price, unit, badge;",
"  final Color color;",
"  const _DItem(this.key, this.emoji, this.label, this.price, this.unit, this.color, this.badge);",
"}",
].join('\n');

fs.writeFileSync(B + '/features/goride/booking/goride_duration_screen.dart', duration, 'utf8');
console.log('duration done');
